In [2]:
import numpy as np
import random
import tensorflow as tf
import torch

In [5]:
print(np.arange(10))
print(torch.arange(10))
print(tf.range(10))

[0 1 2 3 4 5 6 7 8 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [7]:
print(np.eye(3))
print(torch.eye(3))
print(tf.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [9]:
np.random.seed(2024)

arr_rand = np.random.rand(3,4)
print(arr_rand)

arr_randint = np.random.randint(-10, 10, size = (3,4))
print(arr_randint)

[[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]]
[[ 5  1 -3  8]
 [-1 -4  0 -9]
 [-5  9 -6 -2]]


In [11]:
torch.manual_seed(2024)

print(torch.rand(3,4))
print(torch.randint(-10, 10, size = (3, 4)))

tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]])
tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])


In [16]:
tf.random.set_seed(2024)
print(tf.random.uniform((3, 4)))
print(tf.random.uniform((3, 4), minval= -10, maxval= 10, dtype=tf.dtypes.int32))

tf.Tensor(
[[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]], shape=(3, 4), dtype=int32)
