In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
arr_zeros = np.zeros((3, 4))

print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
tensor_zeros = torch.zeros((3, 4))

print(tensor_zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
tf_zeros = tf.zeros((3,4))
print(tf_zeros)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [5]:
arr_zeros = np.ones((3, 4))

print(arr_zeros)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
tensor_ones = torch.ones((3, 4))

print(tensor_ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [8]:
tf_ones = tf.ones((3,4))
print(tf_ones)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [10]:
arr_full = np.full((3, 4), 5)
arr_full

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [11]:
tensor_full = torch.full((3, 4), 5)
tensor_full

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

In [12]:
tf_full = tf.fill((3, 4), 5)
tf_full

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])>